algorithm_name: ppo
anneal_lr: true
clip_coef: 0.025
clip_vloss: true
ent_coef: 0.05
gae: true
gae_lambda: 0.95
gamma: 0.99
learning_rate: 0.00025
max_grad_norm: 2.0
norm_adv: true
num_envs: 8
num_minibatches: 8
num_steps: 256
target_kl: null
update_epochs: 4
vf_coef: 0.0625
