algorithm_name: escher_parallel
batch_size_regret: 512
batch_size_val: 8192
expl: 1.0
infer_device: cpu
iters: 100000000
learning_rate: 0.0005
num_cpus: 8
num_traversals: 500
num_val_fn_traversals: 2000
num_workers: 8
policy_net_train_steps: 1250
policy_network_layers:
- 512
- 512
- 512
regret_network_layers:
- 512
- 512
- 512
regret_train_steps: 1250
train_device: cpu
val_expl: 0.005
val_train_steps: 1250
value_network_layers:
- 512
- 512
- 512
