algorithm_name: ppg
anneal_lr: true
beta_clone: 8.0
clip_coef: 0.2
clip_vloss: true
e_auxiliary: 1
e_policy: 1
ent_coef: 0.1
gae: true
gae_lambda: 0.95
gamma: 0.99
learning_rate: 6.25e-05
max_grad_norm: 2.0
n_aux_grad_accum: 8
n_iteration: 128
norm_adv: true
num_aux_rollouts: 1
num_envs: 8
num_minibatches: 1
num_steps: 64
target_kl: null
update_epochs: 32
v_value: 2
vf_coef: 0.5
