algorithm_name: escher_parallel
batch_size_regret: 1024
batch_size_val: 8192
expl: 1.0
infer_device: cpu
iters: 100000000
learning_rate: 0.002
num_cpus: 8
num_traversals: 8000
num_val_fn_traversals: 250
num_workers: 8
policy_net_train_steps: 80000
policy_network_layers:
- 512
- 512
- 512
regret_network_layers:
- 512
- 512
- 512
regret_train_steps: 20000
train_device: cpu
val_expl: 0.04
val_train_steps: 5000
value_network_layers:
- 512
- 512
- 512
