algorithm_name: ppg
anneal_lr: true
beta_clone: 2.0
clip_coef: 0.8
clip_vloss: true
e_auxiliary: 48
e_policy: 2
ent_coef: 0.05
gae: true
gae_lambda: 0.95
gamma: 0.99
learning_rate: 3.125e-05
max_grad_norm: 2.0
n_aux_grad_accum: 1
n_iteration: 8
norm_adv: true
num_aux_rollouts: 16
num_envs: 8
num_minibatches: 16
num_steps: 16
target_kl: null
update_epochs: 1
v_value: 2
vf_coef: 0.25
