algorithm_name: ppg
anneal_lr: true
beta_clone: 4.0
clip_coef: 0.4
clip_vloss: true
e_auxiliary: 1
e_policy: 1
ent_coef: 0.1
gae: true
gae_lambda: 0.95
gamma: 0.99
learning_rate: 0.000125
max_grad_norm: 0.25
n_aux_grad_accum: 2
n_iteration: 64
norm_adv: true
num_aux_rollouts: 8
num_envs: 8
num_minibatches: 1
num_steps: 512
target_kl: null
update_epochs: 1
v_value: 1
vf_coef: 0.25
