algorithm_name: mmd
anneal_lr: true
clip_coef: 0.8
clip_vloss: true
ent_coef: 0.2
gae: true
gae_lambda: 0.95
gamma: 0.99
kl_coef: 0.2
learning_rate: 0.00025
max_grad_norm: 0.25
norm_adv: true
num_envs: 8
num_minibatches: 1
num_steps: 16
target_kl: null
update_epochs: 4
vf_coef: 1.0
