algorithm_name: nfsp
anticipatory_param: 0.1
batch_size: 64
hidden_layers_sizes:
- 512
- 512
- 512
inner_rl_agent:
  algorithm_name: dqn
  batch_size: 16
  discount_factor: 1.0
  epsilon_decay_duration: 20000000
  epsilon_end: 0.00025
  epsilon_start: 0.03
  learn_every: 10
  learning_rate: 0.0025
  loss_str: mse
  optimizer_str: adam
  replay_buffer_capacity: 500000
  update_target_network_every: 250
learn_every: 128
loss_str: mse
max_steps: None
min_buffer_size_to_learn: 8000
optimizer_str: adam
reservoir_buffer_capacity: 4000000
results_path: ''
rl_learning_rate: 0.01
sl_learning_rate: 0.00125
