algorithm_name: mmd
anneal_lr: true
clip_coef: 0.8
clip_vloss: true
ent_coef: 0.05
gae: true
gae_lambda: 0.95
gamma: 0.99
kl_coef: 0.1
learning_rate: 6.25e-05
max_grad_norm: 0.5
norm_adv: true
num_envs: 8
num_minibatches: 32
num_steps: 32
target_kl: null
update_epochs: 2
vf_coef: 0.0625
