algorithm_name: ppg
anneal_lr: true
beta_clone: 0.125
clip_coef: 0.0125
clip_vloss: true
e_auxiliary: 12
e_policy: 1
ent_coef: 0.1
gae: true
gae_lambda: 0.95
gamma: 0.99
learning_rate: 0.0005
max_grad_norm: 0.25
n_aux_grad_accum: 1
n_iteration: 4
norm_adv: true
num_aux_rollouts: 4
num_envs: 8
num_minibatches: 2
num_steps: 256
target_kl: null
update_epochs: 2
v_value: 2
vf_coef: 1.0
