algorithm_name: ppg
anneal_lr: true
beta_clone: 0.5
clip_coef: 0.2
clip_vloss: true
e_auxiliary: 6
e_policy: 1
ent_coef: 0.05
gae: true
gae_lambda: 0.95
gamma: 0.99
learning_rate: 6.25e-05
max_grad_norm: 0.5
n_aux_grad_accum: 1
n_iteration: 64
norm_adv: true
num_aux_rollouts: 2
num_envs: 8
num_minibatches: 32
num_steps: 16
target_kl: null
update_epochs: 1
v_value: 2
vf_coef: 2.0
